services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  client:
    restart: on-failure
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    depends_on:
      - server
